### ISSUE TITLE
Brackets in title?

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#119]
LP currently has brackets in the website title "[ LearnPlasma ]" 

How do people feel about this? It's definitely unusual, but I also kinda like it.

**Comment by Ro5s** [comment]
👍 Brackets speak to rapid developments to follow in Plasma research (*wip*). Also, visualizing plasma (learning) [fusion and stuff](https://www.conservationinstitute.org/what-is-plasma-energy/) (*why not*):
![screen shot 2018-11-03 at 4 21 34 pm](https://user-images.githubusercontent.com/41117279/47957012-d363a480-df84-11e8-9b31-a4c78641505a.png)
