### ISSUE TITLE
Figure out how to structure content

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#2]
A proper structure for content will be extremely important. How should we group content?

Some possible "tracks" below? Feel free to comment and give suggestions.

- Plasma 101
- Plasma MVP in-depth (problem, solution)
- "Learn Plasma by building one"

**Comment by barrasso** [comment]
I think that's an accurate content structure for the initial release. A more comprehensive track list may look like the following:

- Intro to Plasma (Plasma 101, and explain the differences in naming conventions i.e. Plasma Cash)
- Plasma by Example (Plasma MVP deep dive, provide references to other repos and examples)
- Security Considerations (explain how to balance trade-offs i.e. security vs throughput)
- List of Known Bugs (if any)
- Plasma for Developers (highlight our Plasma abstraction toolkit and provide How-To documentation on it)
