### ISSUE TITLE
🛠 Refactor with static site generator

### ISSUE THREAD

**Issue by tcrowe** [ethsociety/learn-plasma#48]
## Reasoning

The site is appropriately a static website but the pages are currently duplicated. Changing the layout, navigation, and maintaining consistency will be difficult as it grows.

## Proposal

Static site generator with templates

Benefits:
+ Pages authored as simple markdown
+ More easily maintainable
+ Ecosystem of plugins
+ Many open source developers know how to use them

Resources
+ https://www.staticgen.com/
+ One I contribute to is https://hexo.io

They are all compatible with Github Pages, Netlify(the current host), and S3 buckets.

---

Your thoughts?

**Comment by kfichter** [comment]
We should absolutely do this. I'll make sure to check through site generators tomorrow and pick some favorites. Thanks for the suggestion 😃

**Comment by tcrowe** [comment]
🏮Plasma 🏮 ➕ Hexo ⬢ = ❤️

*twists arm*

😉

**Comment by therevoltingx** [comment]
Yes plz, having to think about layout and content sucks.

I prefer things that support Markdown style pages.

**Comment by kfichter** [comment]
I'm currently putting together a more thorough content plan for LearnPlasma and then I'll speak with a designer about a better permanent website design. Once that's done, I'd be happy to move everything over a static site generator.

**Comment by kfichter** [comment]
@tcrowe How would you recommend we best use a static site generator if we want to avoid "blogpost" style content?

**Comment by tcrowe** [comment]
Hello again @kfichter. :wave: I've got an experiment going with this which may address that concern.

It's mostly content pages with disparate sources and posts linked on the front page.

See it here: https://fervent-sammet-4b8cc8.netlify.com/en/

I've done a basic google translation trying to implement i18n. It assumes EN, DE, and Traditional Mandarin as the most popular languages for the audience.

Hopefully I can work with @PaulRBerg to find out which sources to pull in for the feed.

**Comment by tcrowe** [comment]
`if we want to avoid "blogpost" style content`

Can you expand on that thought? Do you want to have a more engaging style of content flow down the page?

**Comment by PaulRBerg** [comment]
@tcrowe Would love to help out! Also, eager to add a Romanian translation to the website and share it with my peers, just let me know how I could do it.

Btw is there any channel within a Slack group dedicated to Plasma or specifically learnplasma.org?

**Comment by therevoltingx** [comment]
I think Kelvin means that the generated site shouldn't look like a blog. It should look pretty much like how it looks now in terms of navigation.

This example looks ok to me: https://fervent-sammet-4b8cc8.netlify.com/en/. Seems to need some CSS work.

Curious how this looks and what framework it's using.

The only one i've used is: https://middlemanapp.com/

**Comment by kfichter** [comment]
@tcrowe That example looks awesome. I can definitely rework the CSS.

**Comment by tcrowe** [comment]
Thanks for the feedback and checking out the ideas in my prototype. @PaulRBerg @therevoltingx @kfichter 👍🏼

Do all think it's important or necessary to have support for the other languages? It is more complex but it can be helpful to many users.

Who can we drag in to give aesthetic direction, design, and etc? I'm sure if they want they can drop us images or links here.

@therevoltingx RE: middleman: Here is an authoritative list by Netlify team https://www.staticgen.com. The one I used for the prototype was Hexo. Some considerations on the static generator are 1.) Which language is best for the community? 2.) Who is willing to implement the i18n? 3.) Is everyone able to understand the templating language?

**Comment by tcrowe** [comment]
The original design has:
+ bootstrap - css + js
+ jquery - js
+ font-awesome - css + font icons
+ themify - ?
+ prismjs - syntax highlighting

Utilization was not great. In the future can we think about not using any so we can minimize page load? Or try to minimize what things we drag into the build?

**Comment by therevoltingx** [comment]
@tcrowe 

I personally don't think we should worry about explicitly supporting other languages. There are always plugins or browser-side translation for that. I think it adds more work.

Hexo looks pretty good to me, it has Markdown support which is a bit easier to write.
It may not be as flexible as pure HTML, but I think that's a good thing to make things consistent.

I think Markdown is the perfect language to write tutorial-style content. 

Is there w branch/repo with your work so we can see the layout and raw files? Think we can just update the template a bit and css and it should be good to go.

**Comment by kfichter** [comment]
> I personally don't think we should worry about explicitly supporting other languages. There are always plugins or browser-side translation for that. I think it adds more work.

Although I agree that it's not necessary right now (lot of content in flux), it's absolutely something we should have in the future. Google translate will have a very hard time with technical writing.

**Comment by kfichter** [comment]
> Utilization was not great. In the future can we think about not using any so we can minimize page load? Or try to minimize what things we drag into the build?

Yeah the original design was just some template we had sitting around. We should definitely throw out anything unnecessary.

**Comment by kfichter** [comment]
@therevoltingx looks like the source is available here https://github.com/tcrowe/learn-plasma. Let's start moving things to hexo then :-)

**Comment by tcrowe** [comment]
@therevoltingx RE: `Is there w branch/repo with your work so we can see the layout and raw files?`

https://github.com/tcrowe/learn-plasma

How to replicate:

```sh
git clone -b static-site-hexo https://github.com/tcrowe/learn-plasma.git
cd learn-plasma
npm install

# request blog and github data
# (if you run this a lot github will bark at you for api rate limit)
npm run data

# watch during development, auto-refresh courtesy of browser-sync
npm run dev
open http://127.0.0.1:7781

# build for production
npm run prd

# experimental static site test
npm test
```

**Comment by tcrowe** [comment]
If you want to @kfichter you can create a static site refactor branch and we can each PR into it here. Would that work for everyone?

**Comment by kfichter** [comment]
@tcrowe Let's do that, will get that started right now.

**Comment by tcrowe** [comment]
PR is available here: https://github.com/ethsociety/learn-plasma/pull/77

I put in some of the above and more for development help. If anything breaks or you need clarification I'm happy to help. 🤠👍🏼
