### ISSUE TITLE
Links in FAQ section are broken

### ISSUE THREAD

**Issue by jet86** [ethsociety/learn-plasma#51]
Two of the FAQs have links that currently go nowhere. I would submit a PR to fix them except I'm not confident of the exact destination the links should point to. The relevant links are in following questions:

**How can I contribute to Plasma?**
The link `claiming bounties on Gitcoin` goes nowhere.

**How can I report bugs?**
The link `Post it to Github!` goes nowhere.

**Comment by kfichter** [comment]
Fixed in #53. Thanks for reporting!
