### ISSUE TITLE
Pull "Build" page out into a separate repository

### ISSUE THREAD

**Issue by tcrowe** [ethsociety/learn-plasma#52]
Lets consider turning this:
https://www.learnplasma.org/pages/build.html

Into ➡️ https://github.com/ethsociety/awesome-plasma

The "build" page can be "build" or "ecosystem" in this site. The static generator can pull it in as a submodule or some technique similar to that.

**Comment by PaulRBerg** [comment]
Great idea, but the new repo and the "Build" page could co-exist. On GitHub, more tangential stuff could be added, e.g. a repo documenting and implementing a sparse Merkle tree.

**Comment by kfichter** [comment]
Going to close this for now. Seems like enough work to just manage this ATM.
