### ISSUE TITLE
Compare Pros/Cons, use-cases of Plasma MVP/Cash/Debit

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#54]
As per [this reddit comment](https://www.reddit.com/r/learnplasma/comments/98a7pp/plasma_chain_design/), it would be useful to explore some of the possible use-cases and limitations of Plasma.

This could probably be in the form of a *page comparing the pros and cons of Plasma MVP, Plasma Cash, and Plasma Debit*, for now.

**Comment by jet86** [comment]
Would it be possible to make a comparison table to compare the features/functions of different Plasma specs?

**Comment by kfichter** [comment]
Yep, absolutely. I believe @evabeylin has started work on a table like that!

**Comment by KY-SmartMesh** [comment]
This will be a great help !
Plasma Cash onward have some very fundamental different, it will be a useful reference for all.

**Comment by barrasso** [comment]
Resolved in #94
