### ISSUE TITLE
Site Redirection to HTTPS

### ISSUE THREAD

**Issue by jet86** [ethsociety/learn-plasma#57]
I noticed the following recently:

- http://learnplasma.org redirects to http://www.learnplasma.org
- https://learnplasma.org times out

I believe it would be best if all three of the following redirected to https://www.learnplasma.org

- http://learnplasma.org
- http://www.learnplasma.org
- https://learnplasma.org

**Comment by barrasso** [comment]
I just updated the DNS records, may take a little while to reflect the changes.

@kfichter Does anything need to be done on the Netlify side of things? Not sure if the automatic SSL provisioning was setup correctly. See: [Netlify Certificates](https://www.netlify.com/docs/ssl/#netlify-certificates)

**Comment by barrasso** [comment]
Looks like http://learnplasma.org now redirects to https://www.learnplasma.org.

However, http://www.learnplasma.org && https://learnplasma.org still do not.

**Comment by kfichter** [comment]
Having an issue with DNS records right now... will try to get fixed and update tonight

**Comment by barrasso** [comment]
All SSL cert and HTTPS redirection issues have been resolved. Thanks for reporting!
