### ISSUE TITLE
Should we include any form of analytics?

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#79]
Site analytics can be extremely useful. Knowing what browsers people are using to view the site can help us clean up broken content. Seeing what countries pages are accessed from can inform decisions about languages for translation. Information about popular pages can tell us what content to expand, and what to keep the same. 

All of this obviously comes at a cost of privacy. Our site currently (to the best of my knowledge... maybe we should double check) doesn't include any third party tracking tools. Scripts like Google Analytics are generally invasive.

So the questions: Is this something we can do? Is this something we *should* do? Can this be done without an invasion of privacy?

I was thinking we might be able to have users explicitly opt-in ("Collect anonymous usage data?") but not sure that would play out. Feedback welcome.

**Comment by barrasso** [comment]
I agree with Miguel’s comment. 

It would be useful to include some form of website analytics as long as the metadata collected is non-invasive.

**Comment by pet3r-pan** [comment]
Yeah I think its fine as there isn't anything _too_ sensitive on the site that can be connected with individuals

**Comment by kfichter** [comment]
Ok, will add an analytics script. If it ends up being invasive, will remove.
