### ISSUE TITLE
Include links to Plasma implementations

### ISSUE THREAD

**Issue by kfichter** [ethsociety/learn-plasma#8]
Questions:
- Should we link to any available implementation or just actively maintained?
- Can someone find a list of implementations?

**Comment by kfichter** [comment]
Some links, from ethresear.ch:

https://github.com/wolkdb/deepblockchains/tree/master/Plasmacash

https://github.com/voltairelabs/plasma

https://github.com/omisego/plasma-mvp

https://github.com/omisego/plasma-cash

https://github.com/loomnetwork/plasma-erc721

https://github.com/FourthState

https://github.com/ethereum-plasma/plasma

https://github.com/BANKEX/PlasmaParentContract

**Comment by maxweng** [comment]
Let's put all links here. I'm also working on a Plasma DEX https://github.com/FastXProtocol/plasma-mvp

**Comment by barrasso** [comment]
I will include a "Known Implementations" list in the docs. I think we should only link to actively maintained implementations to minimize noise and maximize code reliability.

**Comment by kfichter** [comment]
Reopening to get some more links

**Comment by tpmccallum** [comment]
LayerXcom's Vyper implementation of Plasma
https://github.com/LayerXcom/plasma-mvp-vyper
