### ISSUE TITLE
Link to curated list of known Plasma implementers? 

### ISSUE THREAD

**Issue by zach-is-my-name** [ethsociety/learn-plasma#86]
I remember such a list being mentioned as connected to learnplasma

In general, having such a list with known implementers would be incredibly helpful for Plasma and the teams/individuals learning Plasma

**Comment by KY-SmartMesh** [comment]
Where did you see this list ? @zach-is-my-name

**Comment by zach-is-my-name** [comment]
https://github.com/ethsociety/learn-plasma/issues/8

Opened the issue because I didn't see it on the live site.  If it's there
should be made prominent

**Comment by kfichter** [comment]
The page is here: https://www.learnplasma.org/pages/build.html

Maybe we should rename and change some of the text on this page to make it more clear.

**Comment by zach-is-my-name** [comment]
Ah yes. Thank you.  Section named “Build” is a great call to action, but to me implies “you build”,  not “they built” or “they are building”. Which to me speaks to the point of learnplasma ie. to communicate that you are not solely responsible for bootstrapping a plasma system from scratch (conceptually).  Let’s get you up to speed so you can either understand the type of systems you may be participating in one day, or graduate you to ethresearch so you may contribute to the body of knowledge
